### ISSUE TITLE
Annoying console.log

### ISSUE THREAD

**Issue by pjaworski1402** [dropzone-ui/react-dropzone#172]
**Describe the bug**
on any action, console.log is called
![image](https://user-images.githubusercontent.com/67292005/144764820-f508870e-b21d-4162-b674-19d2edcfc779.png)

"hideViewIcon false" on DropzoneHeader.tsx:41

**To Reproduce**
Do any action on <Dropzone />

**Comment by JinSSJ3** [comment]
Hi @pjaworski1402. We are really sorry about that annoying behaviour.

We are publishing 🚀  a new version [dropzone-ui 6.3.0](https://www.npmjs.com/package/@dropzone-ui/react) solving this problem and also adding some extra features. 
We'd like you to reinstall the package to enjoy the changes. 💻 

regards,
Dropzone-ui team.
